version: "2"

run:
  issues-exit-code: 1
  tests: false

linters:
  enable:
    - gocognit
    - gosec
    - revive
  settings:
    gocognit:
      min-complexity: 7
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      rules:
        - name: exported
        - name: unused-parameter
        - name: unreachable-code
        - name: context-as-argument
        - name: error-return
        - name: error-strings
        - name: error-naming
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - all
        path: api/gen/
      - linters:
          - gosec
        source: ^fmt\.F
        text: G104
